### ISSUE TITLE
Error messages not returned from ami_manager:originate

### ISSUE THREAD

**Issue by ambrish33** [pbxware/lua-ami#2]
When testing the interactive-test.lua getti ng the below error when the user is not configured in the manager.conf of asterisk:

lua: /usr/lib/lua/5.1/ami/login.lua:29: attempt to concatenate local 'err' (a nil value)
stack traceback:
        /usr/lib/lua/5.1/ami/login.lua:29: in function 'challenge_login'
        /usr/lib/lua/5.1/ami.lua:142: in function </usr/lib/lua/5.1/ami.lua:128>
        (tail call): ?
        /usr/lib/lua/5.1/ami.lua:93: in function 'originate'
        interactive-test.lua:28: in main chunk
        [C]: ?

However if there is a authentication failure the error is properly returned:
AMI IN: Response: Error
AMI IN: Message: Authentication failed
AMI IN:
ERROR   AMI login failed: Authentication failed

**Comment by litnimax** [comment]
Hi!
This is not supported.
We used it long ago in some projects.
I guess the problem is in AMI version - this is outdated..
